# Generated by Django 4.0.5 on 2022-06-27 06:14

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('email', models.CharField(max_length=50, verbose_name='correo del cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='dirrecion')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('password', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id especie')),
                ('nombreEspecie', models.CharField(max_length=69, verbose_name='nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('nombreDueño', models.CharField(max_length=50, verbose_name='Nombre del dueño')),
                ('imagenMascota', models.ImageField(upload_to=app.models.filepath, verbose_name='imagen de la mascota')),
                ('nombreEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie', verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCliente',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id carrito')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota', verbose_name='Mascota')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
