# Generated by Django 4.0.5 on 2022-07-15 04:05

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCliente',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='correo del cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='dirrecion')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('password', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id especie')),
                ('nombreEspecie', models.CharField(max_length=69, verbose_name='nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('nombreDueño', models.CharField(max_length=50, verbose_name='Nombre del dueño')),
                ('imagenMascota', models.ImageField(upload_to=app.models.filepath, verbose_name='imagen de la mascota')),
                ('nombreEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie', verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='CompraRealizada',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id compra')),
                ('seguimiento', models.BooleanField(default=False, verbose_name='Seguimiento')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carritocliente', verbose_name='Carrito')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='carritocliente',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='carritocliente',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
