# Generated by Django 4.0.5 on 2022-06-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id especie')),
                ('nombreEspecie', models.CharField(max_length=69, verbose_name='nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('nombreDueño', models.CharField(max_length=50, verbose_name='Nombre del dueño')),
                ('imagenMascota', models.ImageField(upload_to='', verbose_name='imagen de la mascota')),
                ('nombreEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie', verbose_name='Especie')),
            ],
        ),
    ]
