# Generated by Django 4.0.5 on 2022-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagenMascota',
            field=models.ImageField(upload_to='img/', verbose_name='imagen de la mascota'),
        ),
    ]
