# Generated by Django 4.0.5 on 2022-07-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carritocliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritocliente',
            old_name='id_cliente',
            new_name='id_user',
        ),
    ]
