# Generated by Django 4.0.5 on 2022-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mascota_imagenmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagenMascota',
            field=models.ImageField(upload_to='', verbose_name='imagen de la mascota'),
        ),
    ]
