# Generated by Django 4.0.5 on 2022-06-13 09:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mascota_imagenmascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagenMascota',
            field=models.ImageField(upload_to=app.models.filepath, verbose_name='imagen de la mascota'),
        ),
    ]
