# Generated by Django 4.0.4 on 2022-06-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_mascota_edad_mascota_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id cliente')),
            ],
        ),
    ]
