# Generated by Django 4.0.4 on 2022-06-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id',
            new_name='id_mascota',
        ),
        migrations.CreateModel(
            name='CarritoCliente',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id carrito')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota', verbose_name='Mascota')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
